### ISSUE TITLE
whats the diff between nocom and noc*m

### ISSUE THREAD

**Issue by master7720** [EBSmash/CousinWareAdditions#3]

**Comment by EBSmash** [comment]
noc*m sends CPacketTryUseItemOnBlock instead of the original nocoms CPacketPlayerDigging

**Comment by master7720** [comment]
Ah ok thanks

**Comment by master7720** [comment]
> noc*m sends CPacketTryUseItemOnBlock instead of the original nocoms CPacketPlayerDigging

wait so noc*m is better then nocom

**Comment by EBSmash** [comment]
it just works on 0b0t. but its also slower
